--SELECT * FROM EmployeeDemographics
--SELECT FirstName, LastName FROM EmployeeDemographics
--SELECT TOP 5 * FROM EmployeeDemographics
--SELECT DISTINCT(Gender) FROM EmployeeDemographics
--SELECT COUNT(Gender) FROM EmployeeDemographics
--SELECT COUNT(LastName) AS LastNameCount FROM EmployeeDemographics
--SELECT MAX(Salary) FROM EmployeeSalary
--SELECT MIN(Salary) FROM EmployeeSalary
--SELECT AVG(Salary) FROM EmployeeSalary